/* 
 * My API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines PasswordStrength
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum PasswordStrength
    {
        /// <summary>
        /// Enum NoComply for value: 0
        /// </summary>
        [EnumMember(Value = "0")]
        NoComply = 0,
        /// <summary>
        /// Enum VeryWeak for value: 1
        /// </summary>
        [EnumMember(Value = "1")]
        VeryWeak = 1,
        /// <summary>
        /// Enum Weak for value: 2
        /// </summary>
        [EnumMember(Value = "2")]
        Weak = 2,
        /// <summary>
        /// Enum Medium for value: 3
        /// </summary>
        [EnumMember(Value = "3")]
        Medium = 3,
        /// <summary>
        /// Enum Strong for value: 4
        /// </summary>
        [EnumMember(Value = "4")]
        Strong = 4    }
}
