/* 
 * My API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// PasswordCheckResult
    /// </summary>
    [DataContract]
        public partial class PasswordCheckResult :  IEquatable<PasswordCheckResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PasswordCheckResult" /> class.
        /// </summary>
        /// <param name="passwordStrength">passwordStrength.</param>
        /// <param name="message">message.</param>
        /// <param name="breachCount">breachCount.</param>
        public PasswordCheckResult(PasswordStrength passwordStrength = default(PasswordStrength), string message = default(string), int? breachCount = default(int?))
        {
            this.PasswordStrength = passwordStrength;
            this.Message = message;
            this.BreachCount = breachCount;
        }
        
        /// <summary>
        /// Gets or Sets PasswordStrength
        /// </summary>
        [DataMember(Name="passwordStrength", EmitDefaultValue=false)]
        public PasswordStrength PasswordStrength { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets BreachCount
        /// </summary>
        [DataMember(Name="breachCount", EmitDefaultValue=false)]
        public int? BreachCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PasswordCheckResult {\n");
            sb.Append("  PasswordStrength: ").Append(PasswordStrength).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  BreachCount: ").Append(BreachCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PasswordCheckResult);
        }

        /// <summary>
        /// Returns true if PasswordCheckResult instances are equal
        /// </summary>
        /// <param name="input">Instance of PasswordCheckResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PasswordCheckResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PasswordStrength == input.PasswordStrength ||
                    (this.PasswordStrength != null &&
                    this.PasswordStrength.Equals(input.PasswordStrength))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                ) && 
                (
                    this.BreachCount == input.BreachCount ||
                    (this.BreachCount != null &&
                    this.BreachCount.Equals(input.BreachCount))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PasswordStrength != null)
                    hashCode = hashCode * 59 + this.PasswordStrength.GetHashCode();
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                if (this.BreachCount != null)
                    hashCode = hashCode * 59 + this.BreachCount.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
